[package]
name = "fabparse"
version = "0.1.0"
edition = "2021"
description = "A minimized parser combinator library"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
smallvec = "1.11.2"
